### ISSUE TITLE
Transparent parts don't trigger roof hiding

### ISSUE THREAD

**Issue by caerandir** [VanceCole/roofs#9]
The module is awsome! Just one issue(?): I wanted to have the roof getting invisible even when the player approches the building, ~3 grid units away. So I created a webp file with a transparant layer larger by that amount than the actual roof. To my surprise, the roof vaished only when the player touched the non-transparent image part. What worked in the end is to not have a complete transparant layer, but a white layer with opacity of 1.5% - this was "opaque" enough to trigger the roof hiding. It is barely visible, so it's OK, but I was wondering if this is by design.

**Comment by silvative** [comment]
This one's intentional- it enables things like courtyards or non-square roofs in general. For example, imagine an L shaped roof- you wouldn't want it to disappear if someone was outside but within the "elbow". Hope that makes sense, and your solution sounds really creative!

**Comment by caerandir** [comment]
OK, understand the reasoning, makes sense. Case closed. However, would it be possible and easy to implement a padding, i.e. a border around the roof tile that already triggers the visibility change? If not, I'm fine with my solution.
